### ISSUE TITLE
Visual studio market place tags

### ISSUE THREAD

**Issue by jollygardener** [arbs-io/api-studio-visualstudio#27]
Great extension 👍 
Would be good to add the _swagger_ tag in the VS marketplace- I was trying to find this using tags.

**Comment by arbs-io** [comment]
> Great extension 👍 
> 
> Would be good to add the _swagger_ tag in the VS marketplace- I was trying to find this using tags.

Brilliant, many thank and much appreciated. I'd updated the tags but didn't reply. Apologies.
