### ISSUE TITLE
error when opening ApiStudio designer: Could not find file Default.ApiStudio.XML

### ISSUE THREAD

**Issue by sorenbargmann** [arbs-io/api-studio-visualstudio#64]

**Comment by arbs-io** [comment]
Hi @sorenbargmann 
Many thanks for raising the issue. 
A couple of questions:
- Is this happening when you create a new project, if yes which type (AzFunc)?. 
- If possible could you post a sample project if you have one that you could share?

**Comment by arbs-io** [comment]
To note that Default.ApiStudio is an xml file. But there shouldn't be any file called Default.ApiStudio.xml within the project.

**Comment by arbs-io** [comment]
I need more info to try and help resolve this issue. I've verified with multiple users and this seems isolated. Please open a new ticket with more information if the issue occurs again.

**Comment by arbs-io** [comment]
I need more info to be able to investigate the issue you've experienced
