### ISSUE TITLE
Serialize as API Blueprint language instructions

### ISSUE THREAD

**Issue by jzabroski** [arbs-io/api-studio-visualstudio#65]
https://apiblueprint.org/

**Comment by arbs-io** [comment]
Hi @jzabroski 
What is the ask here? 
Is this just an advertisement for blueprint or do you think that blueprint support should be added?

**Comment by jzabroski** [comment]
I am unaware of another format for prototyping and testing a new API. The idea of an API Studio seems like a step beyond.

I'm not advertising. I'm not sure how I heard about them but I think someone asked me to basically duplicate someone else's rest API, literally "sent me the API blueprint" to make it clear they wanted an exact copy, and I hard passed for ethical reasons.

**Comment by arbs-io** [comment]
Thanks for reaching out! The tool is a visual studio extension that provides an easy and fast method to design APIs. This approach allows prototyping and testing APIs quickly. The tool uses a dsl that templates standard RESTful semantics whilst allowing override when standard http requests are required. The output is csharp currently and hooks into external libs to generate OpenAPI specification. As for duplicating someone else's REST API, I completely understand your decision to pass on the demand for ethical reasons. It's essential to maintain integrity in our work and avoid any actions that could be considered unethical or violate laws or regulations.

**Comment by arbs-io** [comment]
Closing: I don't believe this thread is directly related to an issue in the source
